<?xml version='1.0'?>
<algebraList>
<algebra>
 <basicAlgebra>
  <algName>CIB5-1</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-2</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-3</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-4</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 2, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-5</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-6</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-7</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-8</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-9</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-10</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-11</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-12</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-13</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-14</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-15</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-16</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-17</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-18</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-19</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-20</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-21</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-22</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-23</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-24</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-25</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 3, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-26</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-27</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-28</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-29</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-30</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-31</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-32</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-33</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-34</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-35</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-36</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-37</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-38</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-39</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-40</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 3, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-41</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 0, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-42</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-43</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-44</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-45</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-46</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-47</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-48</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-49</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-50</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-51</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-52</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-53</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-54</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-55</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-56</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-57</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-58</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-59</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-60</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-61</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 1, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 3, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-62</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 3, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-63</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-64</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 3, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-65</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 3, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-66</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-67</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-68</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-69</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-70</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 3, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-71</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-72</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-73</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-74</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-75</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-76</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-77</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-78</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-79</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-80</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-81</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-82</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 3, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-83</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-84</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-85</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-86</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-87</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-88</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-89</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-90</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-91</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-92</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-93</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-94</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-95</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-96</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-97</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-98</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-99</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 1, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-100</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-101</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-102</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-103</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-104</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-105</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>1, 2, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-106</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-107</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-108</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-109</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-110</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-111</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-112</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-113</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 1, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-114</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>2, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-115</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>2, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-116</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-117</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-118</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>2, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-119</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>2, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 3, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-120</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 0, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-121</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>2, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-122</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 2, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-123</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 3, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-124</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>2, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-125</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>2, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-126</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>2, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-127</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>2, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-128</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>2, 4, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-129</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>2, 4, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-130</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>2, 2, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-131</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-132</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>2, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 2, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-133</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-134</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-135</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>2, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 2, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-136</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>2, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-137</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>2, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-138</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>2, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>3, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-139</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>2, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-140</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>2, 2, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-141</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>2, 2, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-142</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>2, 2, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-143</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 2, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>2, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-144</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>4, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-145</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>4, 0, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-146</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-147</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-148</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-149</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>4, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-150</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>4, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-151</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-152</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-153</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-154</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-155</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 2, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-156</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-157</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-158</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 3, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-159</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>4, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-160</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-161</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-162</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>1, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>4, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-163</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-164</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-165</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>4, 0, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 2, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-166</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>4, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 3, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-167</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-168</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 1, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 2</row>
      <row r='&quot;[2]&quot;'>1, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>4, 2, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>3, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-169</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 0, 2</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-170</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 0, 3</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-171</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-172</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 2</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-173</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 3</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-174</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 4, 2</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-175</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 4, 2</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-176</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 4, 3</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-177</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-178</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-179</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-180</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 3</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-181</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-182</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-183</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-184</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 0</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-185</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 2</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-186</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-187</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>1, 2, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-188</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-189</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-190</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 2</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-191</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 4, 3</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>1, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-192</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 1, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 4, 0</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 1, 1</row>
      <row r='&quot;[3]&quot;'>1, 4, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-193</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 0, 2</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-194</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 0, 3</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-195</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 0, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-196</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-197</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 3</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-198</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 3</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 2, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-199</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>4, 0, 0, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-200</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-201</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-202</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 2</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-203</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 0, 0</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 0, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-204</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-205</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>4, 4, 4, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 0, 1, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-206</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 2</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 4, 0</row>
      <row r='&quot;[3]&quot;'>4, 4, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 2, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-207</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 0, 3</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 2</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 2, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-208</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 4, 3</row>
      <row r='&quot;[3]&quot;'>4, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-209</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 3</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>4, 2, 4, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-210</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>4, 0, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-211</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 0, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-212</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 1, 1</row>
      <row r='&quot;[3]&quot;'>4, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-213</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 2</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 4, 0</row>
      <row r='&quot;[2]&quot;'>3, 3, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>4, 4, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>2, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-214</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 0, 1</row>
      <row r='&quot;[3]&quot;'>4, 2, 0, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-215</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 0, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>4, 2, 1, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 0, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-216</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 3, 4, 3</row>
      <row r='&quot;[1]&quot;'>2, 1, 4, 2, 0</row>
      <row r='&quot;[2]&quot;'>3, 4, 2, 4, 1</row>
      <row r='&quot;[3]&quot;'>4, 2, 4, 3, 1</row>
      <row r='&quot;[4]&quot;'>3, 0, 1, 1, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-217</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 4, 2, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 0, 0, 3</row>
      <row r='&quot;[2]&quot;'>4, 0, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>2, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-218</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 4, 2, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 0</row>
      <row r='&quot;[2]&quot;'>4, 3, 2, 1, 3</row>
      <row r='&quot;[3]&quot;'>2, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 0, 3, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
<algebra>
 <basicAlgebra>
  <algName>CIB5-219</algName>
  <desc></desc>
  <cardinality>5</cardinality>
  <operations>
   <op>
    <opSymbol>
     <opName>g</opName>
     <arity>2</arity>
    </opSymbol>
    <opTable>
     <intArray>
      <row r='&quot;[0]&quot;'>0, 2, 4, 2, 1</row>
      <row r='&quot;[1]&quot;'>2, 1, 3, 0, 3</row>
      <row r='&quot;[2]&quot;'>4, 3, 2, 1, 0</row>
      <row r='&quot;[3]&quot;'>2, 0, 1, 3, 0</row>
      <row r='&quot;[4]&quot;'>1, 3, 0, 0, 4</row>
     </intArray>
    </opTable>
   </op>
  </operations>
 </basicAlgebra>
</algebra>
</algebraList>



